name: Deploy

on: [push]
#部署
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: cleanup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPSHOST }}
        username: ${{ secrets.VPSUSERNAME }}
        port: ${{ secrets.VPSPORT }}
        password: ${{ secrets.VPSPASSWORD }}
        script: |
          wget get https://raw.githubusercontent.com/chousann/docker-maccms10/main/.github/workflows/prepare.sh -O prepare.sh
          chmod 777 prepare.sh
          bash prepare.sh
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPSHOST }}
        username: ${{ secrets.VPSUSERNAME }}
        port: ${{ secrets.VPSPORT }}
        password: ${{ secrets.VPSPASSWORD }}
        source: "*"
        target: "/root/docker-maccms10"
        
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPSHOST }}
        username: ${{ secrets.VPSUSERNAME }}
        port: ${{ secrets.VPSPORT }}
        password: ${{ secrets.VPSPASSWORD }}
        script: |
          cd docker-maccms10
          chmod 777 .github/workflows/deploy.sh
          bash .github/workflows/deploy.sh
          