name: Deploy

on: [push]
#部署
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPSHOST }}
        USERNAME: ${{ secrets.VPSUSERNAME }}
        PORT: ${{ secrets.VPSPORT }}
        KEY: ${{ secrets.VPSPASSWORD }}
        script: touch access.txt
